language: node_js

services: docker

script:
  - ci_env=`bash <(curl -s https://codecov.io/env)`
  - docker build --no-cache -t bluetooth-client client
  - docker run $ci_env bluetooth-client npm run travis
  - docker build --no-cache -t bluetooth-auth-server auth-server
  - docker run $ci_env bluetooth-auth-server npm run travis
